version: '3.8'

services:
  sso-app-dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_COMMIT=${GIT_COMMIT:-dev}
        - BUILD_DATE=${BUILD_DATE:-$(date -u +"%Y-%m-%dT%H:%M:%SZ")}
        - VERSION=${VERSION:-dev}
    container_name: sso-app-dev
    restart: unless-stopped
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - DATABASE_URL=sqlite:///data/sso_test_dev.db
      - RP_ID=${RP_ID:-localhost}
      - RP_NAME=${RP_NAME:-SSO Test App (Dev)}
      - ORIGIN=${ORIGIN:-http://localhost:5000}
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - sso_dev_data:/app/data
    networks:
      - dev_network
    command: ["python", "app.py"]

volumes:
  sso_dev_data:
    driver: local

networks:
  dev_network:
    driver: bridge